trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build_and_Test
  displayName: 'Build and Test'
  jobs:
  - job: Build
    displayName: 'Build the project'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
        displayName: 'Install Node.js'

    - script: |
        npm install
      displayName: 'Install dependencies'

    - script: |
        npm run build
      displayName: 'Build the project'

  - job: Test
    displayName: 'Run tests'
    steps:
    - script: |
        npm test
      displayName: 'Run tests'

    - script: |
        npm run coverage
      displayName: 'Generate code coverage'

- stage: Static_Analysis
  displayName: 'Static Analysis'
  jobs:
  - job: Static_Analysis
    displayName: 'Run static analysis'
    steps:
    - script: |
        npm run lint
      displayName: 'Run static analysis'
